### ISSUE TITLE
ItemPool runs out of rupees to remove when adjusting for small keys

### ISSUE THREAD

**Issue by MichaelWolverineStream** [aerinon/ALttPDoorRandomizer#103]
This becomes apparent in TFH + Shopsanity.
The iterable in ItemPool.py:
 `pool.remove(next(iter([x for x in pool if x in ['Rupees (20)', 'Rupees (5)', 'Rupee (1)']])))` 
runs out of rupees to replace and returns a StopIteration exception that isn't dealt with.

I suggest including Bombs (3) and Arrows(10) as replacement items as a fallback for when this limit is reached, as this seems to happen quite often with these settings.

**Comment by aerinon** [comment]
I believe this has been dealt with.
