### ISSUE TITLE
Copyright issue with 001.link.1.zspr

### ISSUE THREAD

**Issue by Berserker66** [aerinon/ALttPDoorRandomizer#108]
The file https://github.com/aerinon/ALttPDoorRandomizer/blob/DoorDev/data/sprites/official/001.link.1.zspr contains over 28000 Bytes directly copied from the A Link to the Past Rom, the same file on https://alttpr.com/sprites now gives an access denied error, AWS is citing a copyright infringement. This file should be purged from all repositories to avoid further copyright issues.

I have addressed the issue in https://github.com/ArchipelagoMW/Archipelago/commit/b8c7d6a72fd47ab90d43b81f671545f1c3fbc18f and some following commits in my project.

**Comment by aerinon** [comment]
Has been removed from the repo
