### ISSUE TITLE
Graphically glitched tiles

### ISSUE THREAD

**Issue by aerinon** [aerinon/ALttPDoorRandomizer#13]
Seen in Hera most usually in holes, so a byproduct of the staircase code maybe?

I have seen it on the Hyrule Castle Boomerang chest, when coming in the Armory Down Stairs, but was not consistently reproducible.

**Comment by EnderofGames** [comment]
I saw it twice in Swamp Palace, while streaming the same seed with someone. Happens after using a staircase both times.  

[Here's a clip of it happening on his side.](https://clips.twitch.tv/LaconicStupidBobaTinyFace) I wasn't streaming myself, but I had similar looking gfx glitch in the same place, as well as another place in Swamp Palace. 

Seed was 788737164. I can get this file if seed isn't enough, and can also get my own video proof at a later time if that would be easier/required.

**Comment by aerinon** [comment]
This happens frequently enough after traversing a staircase that I have no problem finding example of it. As it is mostly cosmetics, I've de-prioritized it until I solve generation and key issues.

**Comment by EnderofGames** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/17417666/73119288-f1684c80-3f1c-11ea-93c6-98da287d2f1a.gif)

Found this one recently. It only appeared on the dark layer, and only while looking up. It might help with finding the source- or maybe it won't and I'm wasting your time.

**Comment by aerinon** [comment]
I believe this has been fixed.
