### ISSUE TITLE
Camera Locking Issue Causing EG Problems

### ISSUE THREAD

**Issue by codemann8** [aerinon/ALttPDoorRandomizer#17]
I'm not entirely positive that this isn't just an issue with the vanilla game, but I had this strange thing happen to me in MM today:

https://clips.twitch.tv/FurryNeighborlyPorcupinePipeHype

**Comment by aerinon** [comment]
For now, reset your camera if you notice this happening. I will try to get around to figuring this out eventually. (Probably Feb. at the earliest at this rate.)

**Comment by aerinon** [comment]
I believe the camera issues have been resolved
