### ISSUE TITLE
Ganon Silvers Hint Gave False Information

### ISSUE THREAD

**Issue by EnderofGames** [aerinon/ALttPDoorRandomizer#20]
Sorry, no screenshot or video on this one, but as I've been posting, I can come back and get it if you require. 

The person I ran the seed with looked up Silvers before going to GT because they didn't want to fight Ganon Silverless. He used the spoiler log that was created with the seed. He read that Silvers were in Mimic Cave, then went and found them. 

I went to Ganon, and at the beginning of phase 3, Ganon says "Did you find the silver arrows in Palace of Darkness?" 

Bow was in PoD, so maybe that related. Are silvers and bow progressive now, and the silver hints broken? Anyways. the hint was incorrect and luckily I knew they were not there.  

Seed was 788737164. I can get this file if seed isn't enough, and can also get my own video proof at a later time if that would be easier/required.

**Comment by aerinon** [comment]
Yeah, I realize I have this error. I hope to update to a newer version of ER soon that likely has already fixed this.

**Comment by aerinon** [comment]
I believe this has been resolved
