### ISSUE TITLE
GT Big Key "Out of 22" in Credits

### ISSUE THREAD

**Issue by EnderofGames** [aerinon/ALttPDoorRandomizer#21]
I doubt you'd change the GT Big Key collection detection in Door Shuffle, but because of the door shuffle the second number can be changed to 27- for accuracy ;)

**Comment by aerinon** [comment]
As this is just cosmetic, I probably won't get around to fixing this for a while. (And in cross-dungeon mode the amount of chests in GT will likely change.)

**Comment by aerinon** [comment]
Fixed in latest unstable
