### ISSUE TITLE
"Hyrule Castle Cannot Reach Sanctuary" Error on Seed Creation

### ISSUE THREAD

**Issue by EnderofGames** [aerinon/ALttPDoorRandomizer#22]
Error happens ~4/5 times with Standard game mode and basic door shuffle. I haven't tried the crossed shuffle, but would expect the same issue. 

Adding this for both the issue tracking, and for helping people who get this error and don't realize that it is _Standard_ mode doing this. Just switch to Open mode. 

If you are trying to make a Standard multiworld, it will load for a while before telling you there is a problem, so making these types of seeds for a lot of people can be really problematic.

**Comment by aerinon** [comment]
Standard mode is broken at the moment. Will update this when I get around to fixing it.

**Comment by aerinon** [comment]
Standard should work much better now.
