### ISSUE TITLE
Cannot Generate Crossed Door Seed w/ GT Open at <7 Crystals

### ISSUE THREAD

**Issue by EnderofGames** [aerinon/ALttPDoorRandomizer#25]
As title says, I've messed around a bit and found this to be true. Basic door shuffling has no problem, and no other real options on (no keysanity, no entrance, no retro). 

The errors that show when this happens are often different. "No possible neutralizers left", "Generation taking too long" (sometimes referencing GT, sometimes Aga's Tower), "Invalid dungeon". I tried about 50 seeds, never got one to generate, everywhere from 0 to 6 crystals.

**Comment by Berserker66** [comment]
I can confirm the reverse to be true. Generated plenty of seeds with any crystal count. However I roll thousands at a time.

**Comment by Berserker66** [comment]
[DR_M343007746_Spoiler.txt](https://github.com/aerinon/ALttPDoorRandomizer/files/4143242/DR_M343007746_Spoiler.txt)

**Comment by EnderofGames** [comment]
I redownloaded the files, put them in a separate folder to test. The original group was downloaded on January 10th. Switched crystals to open GT down to "5", door shuffle algorithm to "crossed", generate ROM and "No more branching candidates!". Switched crystals to open GT to "0", generated again, program hasn't done anything for 5 minutes yet. 

I am using Windows 10, what OS do you use Berserker?

**Comment by Berserker66** [comment]
That's perfectly normal. A lot of seeds die. The spoiler log up there was Seed attempt #2700 or thereabouts.

**Comment by aerinon** [comment]
Known issue:
https://docs.google.com/document/d/1Bk-m-QRvH5iF60ndptKYgyaV7P93D3TiG8xmdxp_bdQ
