### ISSUE TITLE
base2current does not support delta patching

### ISSUE THREAD

**Issue by Berserker66** [aerinon/ALttPDoorRandomizer#57]
Your base2current file https://github.com/aerinon/ALttPDoorRandomizer/blob/DoorDevUnstable/data/base2current.json contains copied Nintendo code that was moved in the MSU update. As the json file simply applies additions and cannot handle moving existing data, this replicates Nintendo owned code in a public repository. This is potentially very bad.

**Comment by aerinon** [comment]
BPS is now in Unstable
