### ISSUE TITLE
module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by snex** [aerinon/ALttPDoorRandomizer#81]
According to https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8, time.clock() has been removed from Python 3.8. Please update code to take account of this deprecated method.

**Comment by cassidoxa** [comment]
Some more information may be helpful here such as which branch and commit you're on. As far as I know time.clock() was already removed and replaced with perf_counter().

**Comment by snex** [comment]
I am on the "master" branch.

**Comment by tcprescott** [comment]
Use the DoorDev branch

**Comment by snex** [comment]
That gives all sorts of other errors but might be on my end. Will investigate some.
