### ISSUE TITLE
Horizontal scrolling not locked in Desert cannonball room

### ISSUE THREAD

**Issue by Tragetaschen** [aerinon/ALttPDoorRandomizer#87]
VOD: https://www.twitch.tv/videos/926774950?t=03h27m11s

While the player moves around the room, Link remains in the center of the screen showing adjacent rooms to the left and right (including some enemy spawn).

The vanilla Desert room doesn't have any horizontal scrolling.

**Comment by aerinon** [comment]
Should be fixed in latest push to Unstable. Thanks for the report!
